# Generated by Django 3.1.7 on 2021-04-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'unique_together': {('customer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=82)),
                ('pinchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinchart.pinchart')),
            ],
            options={
                'unique_together': {('pinchart', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=82)),
                ('type', models.CharField(choices=[('BOOL', 'BOOL'), ('32-BIT', '32-BIT'), ('DINT', 'DINT'), ('REAL', 'REAL'), ('STRING', 'STRING'), ('INT', 'INT'), ('16-BIT', '16-BIT')], default='DINT', max_length=10)),
                ('address_template', models.CharField(max_length=1024, verbose_name='Address Template')),
                ('pinchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinchart.pinchart')),
            ],
            options={
                'unique_together': {('pinchart', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Step Number')),
                ('description', models.CharField(default='**Spare Step**', max_length=1024)),
                ('value_bool', models.BooleanField(default=False)),
                ('value_dint', models.IntegerField(blank=True, default=0, null=True)),
                ('value_real', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('value_string', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('value_int', models.IntegerField(blank=True, default=0, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinchart.sequence')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinchart.word')),
            ],
            options={
                'unique_together': {('sequence', 'number')},
            },
        ),
        migrations.CreateModel(
            name='BitDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit', models.IntegerField(verbose_name='Bit number 0-15, or 0-31')),
                ('device', models.CharField(blank=True, max_length=24, null=True)),
                ('description', models.CharField(max_length=1024)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinchart.word')),
            ],
            options={
                'unique_together': {('word', 'bit')},
            },
        ),
    ]
