# Generated by Django 3.1.7 on 2021-04-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitDescriptions',
            new_name='BitDescription',
        ),
    ]
