# Generated by Django 3.1.7 on 2021-04-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0002_auto_20210408_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='address_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
