# Generated by Django 3.1.7 on 2021-04-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0003_sequence_address_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('sequence', 'number', 'word')},
        ),
    ]
