# Generated by Django 3.1.7 on 2021-04-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0004_auto_20210408_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='name_address_template',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
