# Generated by Django 3.1.7 on 2021-04-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0005_sequence_name_address_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinchart',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked for Editing'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked for Editing'),
        ),
    ]
