# Generated by Django 3.1.7 on 2021-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0006_auto_20210409_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinchart',
            name='array_length',
            field=models.IntegerField(default=50, verbose_name='PLC Array Length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequence',
            name='array_length',
            field=models.IntegerField(default=50, verbose_name='PLC Array Length'),
            preserve_default=False,
        ),
    ]
