# Generated by Django 3.1.7 on 2021-04-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0007_auto_20210409_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(max_length=82),
        ),
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('sequence', 'number')},
        ),
        migrations.RemoveField(
            model_name='step',
            name='value_bool',
        ),
        migrations.RemoveField(
            model_name='step',
            name='value_dint',
        ),
        migrations.RemoveField(
            model_name='step',
            name='value_int',
        ),
        migrations.RemoveField(
            model_name='step',
            name='value_real',
        ),
        migrations.RemoveField(
            model_name='step',
            name='value_string',
        ),
        migrations.RemoveField(
            model_name='step',
            name='word',
        ),
        migrations.CreateModel(
            name='StepData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(default=False)),
                ('value_dint', models.IntegerField(blank=True, default=0, null=True)),
                ('value_real', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('value_string', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('value_int', models.IntegerField(blank=True, default=0, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinchart.step')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pinchart.word')),
            ],
            options={
                'unique_together': {('step', 'word')},
            },
        ),
    ]
