# Generated by Django 3.1.7 on 2021-04-24 17:26

from django.db import migrations, models
import pinchart.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0008_auto_20210409_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='group',
            field=models.CharField(blank=True, max_length=82, null=True),
        ),
        migrations.AlterField(
            model_name='bitdescription',
            name='bit',
            field=pinchart.fields.IntegerRangeField(verbose_name='Bit number 0-15, or 0-31'),
        ),
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='pinchart',
            unique_together={('customer', 'controller_ipaddress')},
        ),
    ]
