# Generated by Django 3.1.7 on 2021-04-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0009_auto_20210424_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepdata',
            name='value_b0',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b1',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b10',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b11',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b12',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b13',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b14',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b15',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b16',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b17',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b18',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b19',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b2',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b20',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b21',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b22',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b23',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b24',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b25',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b26',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b27',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b28',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b29',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b3',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b30',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b31',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b4',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b5',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b6',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b7',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b8',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stepdata',
            name='value_b9',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
