# Generated by Django 3.1.7 on 2021-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinchart', '0010_auto_20210429_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinchart',
            name='array_length',
        ),
        migrations.RemoveField(
            model_name='pinchart',
            name='locked',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='array_length',
            field=models.IntegerField(verbose_name='Step Count'),
        ),
    ]
