# Generated by Django 3.1.7 on 2021-04-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('function', models.IntegerField(choices=[(0, 'DOWNLOAD'), (1, 'UPLOAD')])),
                ('status', models.IntegerField(choices=[(0, 'NOT STARTED'), (1, 'IN PROGRESS'), (2, 'ABORTED WITH ERRORS'), (3, 'COMPLETED WITH ERRORS'), (4, 'SUCCESS')], default=0)),
                ('errors', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
