# Generated by Django 3.1.7 on 2021-04-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed On'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'PINCHART'), (1, 'PINCHART-SEQUENCE'), (2, 'DATA BLOCK')], default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='has_errors',
            field=models.BooleanField(default=False, verbose_name='Has Errors'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
